# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4


      - name: Make Arch Package
        uses: nasOS-official/arch-makepkg@0.0.3    
        # with:
        #   gpg: 13FCEF89DD9E3C4F

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.0
            
        with:
          name: build
          path: |
              .
            
          # pkg/i686-elf-binutils/
            
      # - name: Archive Release
      #   working-directory: pkg/i686-elf-binutils/
      #   run: |
      #     sudo zip -9r release.zip . -x .PKGINFO -x .MTREE -x .BUILDINFO
        
      # - name: release
      #   uses: softprops/action-gh-release@v0.1.15
      #   with:
      #     name: GNU Binutils
      #     tag_name: ${{  github.ref_name }}
      #     draft: false
      #     files: |
      #       *.pkg.tar.zst
              
              
